/*
 * LED.c
 *
 *  Created on: Aug 12, 2023
 *      Author: santiagobualo
 */

#include "LED.h"

void LED_Init(void){

	 GPIO_InitTypeDef GPIO_InitStruct = {0};
	  /*Configure GPIO pin : B1_Pin */
	  GPIO_InitStruct.Pin = B1_Pin;
	  GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
	  GPIO_InitStruct.Pull = GPIO_NOPULL;
	  HAL_GPIO_Init(B1_GPIO_Port, &GPIO_InitStruct);

	  /*Configure GPIO pins : LED_DOOR_STATUS_Pin LED_USER_FEEDBACK_Pin */
	  GPIO_InitStruct.Pin = LED_DOOR_STATUS_Pin|LED_USER_FEEDBACK_Pin;
	  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	  GPIO_InitStruct.Pull = GPIO_NOPULL;
	  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

}

void LED_Timeout_Blink(void){
	//HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin, TURN_LED_ON);
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	//HAL_Delay(125); //no puedo usar esto pq se llama desde la interrupcion
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
}

void LED_delay(void){

	int i=0;
	while (i<1000000){
		i++;
	}
}



void LED_KeyboardPress(void)
{
    	HAL_GPIO_TogglePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin); // Toggle The Output (LED) Pin

}


void LED_OPEN_DOOR(void)
{
    	HAL_GPIO_TogglePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin); // Toggle The Output (LED) Pin

}

void LED_Card_Blink(void){
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_ON);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_OFF);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_ON);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_OFF);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_ON);
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_OFF);

}

void LED_Wrong_Pin_Blink(void){
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_ON);
	LED_delay();
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_OFF);
	LED_delay();
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_ON);
	LED_delay();
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_OFF);
	LED_delay();
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_ON);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_ON);
	LED_delay();
	LED_delay();
	HAL_GPIO_WritePin(LED_USER_FEEDBACK_GPIO_Port, LED_USER_FEEDBACK_Pin,TURN_LED_OFF);
	HAL_GPIO_WritePin(LED_DOOR_STATUS_GPIO_Port, LED_DOOR_STATUS_Pin,TURN_LED_OFF);

}

